remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: 🚀 Checkout Cart 🚀
description: Streamline your library inventory management on Airtable with bulk check-outs and check-ins.
google_analytics: [Your Google Analytics tracking ID]
