description: Streamline your library inventory management on Airtable with bulk check-outs and check-ins.
google_analytics: [Your Google Analytics tracking ID]
#show_downloads: true
theme: jekyll-theme-cayman
